### ISSUE TITLE
TypeError: (0 , O.capitalize) is not a function

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1102]
https://sentry.io/keboola/keboola-connection-ui/issues/337971687/

```
TypeError: (0 , O.capitalize) is not a function
  at saveTransformationEditingField (./src/scripts/modules/transformations/ActionCreators.js:357:43)
  at onEditChange (./src/scripts/modules/transformations/react/pages/transformation-detail/TransformationDetailStatic.coffee:128:40)
  at onChange (./src/scripts/modules/transformations/react/pages/transformation-detail/Requires.jsx:68:15)
  at HTMLDocument.nrWrapper (/admin/projects/1218/transformations/bucket/311165559:5:11640)
...
(14 additional frame(s) were not displayed)
```

**Comment by ondrejhlavacek** [comment]
https://sentry.io/keboola/keboola-connection-ui/issues/337971687/
