### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1582]
https://sentry.io/keboola/keboola-connection-ui/issues/432251566/

```
TypeError: Cannot read property 'body' of undefined
  at call (./src/scripts/modules/components/DockerActionsApi.js:23:29)
  at promise (./src/scripts/utils/request.js:13:17)
  at default (./src/scripts/modules/components/DockerActionsApi.js:20:6)
  at getSourceTables (./src/scripts/modules/ex-db-generic/actionsProvisioning.js:379:16)
  at call (./src/scripts/modules/ex-db-generic/actionsProvisioning.js:24:45)
...
(45 additional frame(s) were not displayed)
```

**Comment by ondrejhlavacek** [comment]
https://sentry.io/keboola/keboola-connection-ui/issues/505162286/

**Comment by pivnicek** [comment]
![image](https://user-images.githubusercontent.com/569139/38022422-bd489064-327f-11e8-93e3-3119d7181dc6.png)

**Comment by ujovlado** [comment]
@pivnicek @ondrejhlavacek Do we now when this happen? When sync action for test credentials times out?

**Comment by ondrejhlavacek** [comment]
Na test credentials už mi to nedělá :-(
