### ISSUE TITLE
TypeError: Unable to get property 'get' of undefined or null reference

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2275]
https://sentry.io/keboola/keboola-connection-ui/issues/752693311/

```
TypeError: Unable to get property 'get' of undefined or null reference
  at Anonymous function (webpack://kbcApp/./src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx:254:11)
  at Anonymous function (webpack://kbcApp/./node_modules/immutable/dist/immutable.js:3004:29)
  at Anonymous function (webpack://kbcApp/./node_modules/immutable/dist/immutable.js:1365:1)
  at Ke.prototype.iterate (webpack://kbcApp/./node_modules/immutable/dist/immutable.js:1732:1)
  at We.prototype.iterate (webpack://kbcApp/./node_modules/immutable/dist/immutable.js:1725:1)
...
(30 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-224](https://sentry.io/keboola/keboola-connection-ui/issues/752948782/)

---

Fixed in: a36eb5b
