### ISSUE TITLE
Error: Minified exception occurred; use the non-minified dev environment for the full error message and ...

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2284]
https://sentry.io/keboola/keboola-connection-ui/issues/753907814/

```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (webpack://kbcApp/./node_modules/react/node_modules/fbjs/lib/invariant.js:35:1)
  at findComponentRoot (webpack://kbcApp/./node_modules/react/lib/ReactMount.js:764:475)
  at findReactNodeByID (webpack://kbcApp/./node_modules/react/lib/ReactMount.js:679:1)
  at getNode (webpack://kbcApp/./node_modules/react/lib/ReactMount.js:162:1)
  at getPublicInstance (webpack://kbcApp/./node_modules/react/lib/ReactDOMComponent.js:925:1)
...
(23 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
```

Error. Check render() method of component 'DatatypeFormRow'. Error details: TypeError: Cannot read property 'get' of undefined
--


```

@pivnicek do you have an idea what can cause this?
