### ISSUE TITLE
TypeError: this.props.tables.find(...) is undefined

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2476]
https://sentry.io/keboola/keboola-connection-ui/issues/795884474/?referrer=github_plugin

```
TypeError: this.props.tables.find(...) is undefined
  at _this (webpack://kbcApp/./src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx:195:14)
  at fn (webpack://kbcApp/./src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx:57:44)
  at this (webpack://kbcApp/./node_modules/immutable/dist/immutable.js:1341:1)
  at _this (webpack://kbcApp/./src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx:54:26)
  at this (webpack://kbcApp/./src/scripts/modules/components/react/components/SapiTableSelector.jsx:61:11)
...
(19 additional frame(s) were not displayed)
```

**Comment by kacurez** [comment]
preklikavam to ale nedari sa mi to nejak nasimuovat, ani so zmazanou tabulkou
