### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2913]
https://sentry.io/keboola/keboola-connection-ui/issues/885642956/?referrer=github_plugin

```
TypeError: Cannot read property 'body' of undefined
  at apply (webpack://kbcApp/./src/scripts/modules/storage-explorer/react/components/DataSample.jsx:183:20)
  at tryCatcher (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:5276:1)
  at _settlePromiseFromHandler (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3297:1)
  at _settlePromise (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3354:1)
  at _settlePromise0 (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3399:1)
...
(5 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
@natocTo nekukol by si to potom aj tu? je to podobny pripad (error code 0, takze tiez aborted)

**Comment by natocTo** [comment]
Jo mrknu.
