### ISSUE TITLE
Error: Check render() method of component 'ComponentDetail'.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2955]
https://sentry.io/organizations/keboola/issues/866892506/?project=90575&referrer=github_plugin

```
Error: Check render() method of component 'ComponentDetail'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:29:28)
  at render (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:45:9)
  at _renderValidatedComponentWithoutOwnerOrContext (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:587:1)
  at _renderValidatedComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:607:1)
  at mountComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:220:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
Na detaile komponenty, kde sa daju filtrovat konfiguracie, das do filtra `int-product2(` a spadne to.

vyzera, ze sa to neescapuje.

**Comment by ujovlado** [comment]
_getFilteredConfigurations

**Comment by natocTo** [comment]
Mrknu.
