### ISSUE TITLE
Storage Explorer - Error: Minified exception occurred; use the non-minified dev environment for the full error message and ...

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2994]
https://sentry.io/organizations/keboola/issues/910303978/?project=90575&referrer=github_plugin

```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (webpack://kbcApp/./node_modules/react/node_modules/fbjs/lib/invariant.js:35:1)
  at instantiateReactComponent (webpack://kbcApp/./node_modules/react/lib/instantiateReactComponent.js:64:393)
  at updateChildren (webpack://kbcApp/./node_modules/react/lib/ReactChildReconciler.js:91:1)
  at _reconcilerUpdateChildren (webpack://kbcApp/./node_modules/react/lib/ReactMultiChild.js:220:1)
  at _updateChildren (webpack://kbcApp/./node_modules/react/lib/ReactMultiChild.js:351:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
Toto bol teda na `GET https://connection.keboola.com/v2/storage/files?limit=50`
