### ISSUE TITLE
Google Sheets Writer - Cannot read property 'sheetId' of undefined

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3020]
https://sentry.io/organizations/keboola/issues/918322672/?project=90575&referrer=github_plugin

```
TypeError: Cannot read property 'sheetId' of undefined
  at apply (webpack://kbcApp/./src/scripts/modules/wr-google-sheets/actionsProvisioning.js:109:45)
  at tryCatcher (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:5276:1)
  at _settlePromiseFromHandler (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3297:1)
  at _settlePromise (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3354:1)
  at _settlePromise0 (webpack://kbcApp/./node_modules/bluebird/js/browser/bluebird.js:3399:1)
...
(5 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Tady když se podívám na poslední requesty před chybou, tak všude je vrácené `0`. To si myslím že třeba notebook šel do nějakého úsporného režimu a odpojil wifi ale ještě se tam vykonají nějaký ty requesty, nebo prostě jen blbne internet nebo něco.

Nevím jestli u těchto komponent třeba nekontrolovat `data.status !== 'ok'` místo `data.status === 'error'`. Ale nevím zda zase vždy chodí status OK. Nebo přímo kontrolovat tu věc z kterou pak pracuji. V tomto případě `data.status === 'error' || !data.sheet` třeba. Asi toto druhé se mi líbí více tak by tam mohlo jít toto.
