### ISSUE TITLE
Storage Explorer - Check render() method of component 'DataSample'.

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3079]
https://sentry.io/organizations/keboola/issues/930927030/?project=90575&referrer=github_plugin

```
Error: Check render() method of component 'DataSample'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:29:28)
  at render (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:45:9)
  at _renderValidatedComponentWithoutOwnerOrContext (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:587:1)
  at _renderValidatedComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:607:1)
  at _updateRenderedComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:560:1)
...
(26 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2EH](https://sentry.io/organizations/keboola/issues/930904967/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2EK](https://sentry.io/organizations/keboola/issues/930905162/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2EJ](https://sentry.io/organizations/keboola/issues/930905148/?project=90575&referrer=github_plugin)
