### ISSUE TITLE
Ex-DB-Generic: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3093]
https://sentry.io/organizations/keboola/issues/934128246/?project=90575&referrer=github_plugin

```
TypeError: Cannot read property 'trim' of undefined
  at isValidQuery (webpack://kbcApp/./src/scripts/modules/ex-db-generic/storeProvisioning.js:83:43)
  at isEditingQueryValid (webpack://kbcApp/./src/scripts/modules/ex-db-generic/storeProvisioning.js:246:14)
  at getStateFromStores (webpack://kbcApp/./src/scripts/modules/ex-db-generic/react/pages/query-detail/QueryDetail.jsx:50:28)
  at apply (webpack://kbcApp/./src/scripts/react/mixins/createStoreMixin.js:20:33)
  at emit (webpack://kbcApp/./node_modules/events/events.js:96:1)
...
(25 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2F0](https://sentry.io/organizations/keboola/issues/934131174/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2F1](https://sentry.io/organizations/keboola/issues/934132501/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2F2](https://sentry.io/organizations/keboola/issues/934132525/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2D0](https://sentry.io/organizations/keboola/issues/905484166/?project=90575&referrer=github_plugin)

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2CZ](https://sentry.io/organizations/keboola/issues/905484075/?project=90575&referrer=github_plugin)
