### ISSUE TITLE
Wr-Db: Check render() method of component 'ChangedSinceFilterInput'.

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3110]
https://sentry.io/organizations/keboola/issues/943904114/?project=90575&referrer=github_plugin

```
Error: Check render() method of component 'ChangedSinceFilterInput'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:29:28)
  at render (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:45:9)
  at _renderValidatedComponentWithoutOwnerOrContext (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:587:1)
  at _renderValidatedComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:607:1)
  at mountComponent (webpack://kbcApp/./node_modules/react/lib/ReactCompositeComponent.js:220:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Počátek všech těch errorů je že se nedohledá table mapping a vůbec se tam nepočítá s tím že by se nedohledal.

```js
getTableMapping: (tableId) => getconfigData().getIn(['storage', 'input', 'tables'], List()).find((t) => t.get('source') === tableId),
```

Jak ale dojde k tomu, že mi to tam zobrazuje danou tabulku, ale pak to nedohledá daný mapping to se mi nepovedlo nasimulovat.

Zkoušel jsem to nakonec přímo v daném projektu a tam byly 2 buckety. V jednom byla jedna tabulka a tam to fungovalo OK, a pak druhý bucket tam bylo asi 20 tabulek a házelo to ty errory u každého detailu. Ale nevím co bylo špatně no, když jsem to chtěl zkontrolovat ještě jednou přímo tam, už byla celé konfigurace smazána.

Ještě to budu zkoumat.
