### ISSUE TITLE
Error: Check render() method of component 'TransformationDetail'.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3178]
https://sentry.io/organizations/keboola/issues/969877754/?project=90575&referrer=github_plugin

```
Error: Check render() method of component 'TransformationDetail'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:32:29)
  at render (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:44:9)
  at _renderValidatedComponentWithoutOwnerOrContext (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:796:1)
  at _renderValidatedComponent (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:819:1)
  at _updateRenderedComponent (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:743:1)
...
(33 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
Zatial nebudeme riesit, je to edge case ... viac je popisane v #3217
