### ISSUE TITLE
TypeError: Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3301]
https://sentry.io/organizations/keboola/issues/969926157/?referrer=github_plugin

```
TypeError: Cannot read property 'getHostNode' of null
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactReconciler.js:60:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:381:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactReconciler.js:60:1)
  at updateChildren (webpack://kbcApp/./node_modules/react-dom/lib/ReactChildReconciler.js:111:1)
  at _reconcilerUpdateChildren (webpack://kbcApp/./node_modules/react-dom/lib/ReactMultiChild.js:209:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2M1](https://sentry.io/organizations/keboola/issues/968016727/?referrer=github_plugin)
