### ISSUE TITLE
Wr-Db: Check render() method of component 't'.

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3335]
https://sentry.io/organizations/keboola/issues/982598641/?referrer=github_plugin

```
Error: Check render() method of component 't'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:32:29)
  at render (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:44:9)
  at _renderValidatedComponentWithoutOwnerOrContext (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:796:1)
  at _renderValidatedComponent (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:819:1)
  at _updateRenderedComponent (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:743:1)
...
(33 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Sentry issue: [KEBOOLA-CONNECTION-UI-2N0](https://sentry.io/organizations/keboola/issues/971801842/?referrer=github_plugin)
