### ISSUE TITLE
GoodDataWriter: Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3354]
https://sentry.io/organizations/keboola/issues/1035826985/?referrer=github_plugin

```
TypeError: Cannot read property 'getHostNode' of null
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactReconciler.js:60:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:381:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactReconciler.js:60:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:381:1)
  at getHostNode (webpack://kbcApp/./node_modules/react-dom/lib/ReactReconciler.js:60:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Konkrétně to padlo tu:

https://github.com/keboola/kbc-ui/blob/92b3d396cefc8b1ce96106cb65dfab84c6aebf02/src/scripts/modules/gooddata-writer-v3/adapters/loadTypeAdapter.js#L27

na `.get` na `undefined`.

Nevím zda tam nějak dávat default, moc se mi to nezdá. Je to tam nějaké zamotané pro mě, když edituji nějak tabulku a nechávám si vypsat `storedInputMapping` mám tam třeba 2 prázdné objedky, pak najednou tři, pak 4 objekt už není prázdný. Jak kdyby se tam něco nepotkalo a vždy to vytvářelo nový záznam do toho editu. Což nevím zda nakonec pak vadí teda.
