### ISSUE TITLE
Error: Check render() method of component 'TransformationBucket'.

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3372]
https://sentry.io/organizations/keboola/issues/1046430212/?referrer=github_plugin

```
Error: Check render() method of component 'TransformationBucket'.
  at logError (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:32:29)
  at this (webpack://kbcApp/./src/scripts/utils/ReactErrorHandler.js:44:9)
  at this (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:788:1)
  at this (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:819:1)
  at this (webpack://kbcApp/./node_modules/react-dom/lib/ReactCompositeComponent.js:743:1)
...
(36 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Možná i zde pak pomůže https://github.com/keboola/kbc-ui/pull/3338
I když tam to 404 hodilo. Divný že teda pak se renderovalo ta stránka. Mrknu více ještě.
