### ISSUE TITLE
TypeError: e.get(...).join is not a function

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3421]
https://sentry.io/organizations/keboola/issues/1059174090/?referrer=github_plugin

```
TypeError: e.get(...).join is not a function
  at enhanceTransformation (webpack://kbcApp/./src/scripts/modules/transformations/stores/TransformationsStore.js:26:78)
  at iteratee (webpack://kbcApp/./src/scripts/modules/transformations/stores/TransformationsStore.js:260:26)
  at each (webpack://kbcApp/./node_modules/underscore/underscore.js:186:1)
  at iteratee (webpack://kbcApp/./src/scripts/modules/transformations/stores/TransformationsStore.js:259:13)
  at each (webpack://kbcApp/./node_modules/underscore/underscore.js:186:1)
...
(16 additional frame(s) were not displayed)
```

**Comment by yustme** [comment]
Mám k tomu tady ticket, že někomu nejde zobrazit stránka s transformacema:
https://keboola.zendesk.com/agent/tickets/10692 . Bylo by fajn to nasadit teda.
