### ISSUE TITLE
[wr-db] TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#767]
https://sentry.io/keboola/keboola-connection-ui/issues/193567404/

```
TypeError: Cannot read property 'get' of undefined
  at updateProtectedProperties (./src/scripts/modules/wr-db/v2-actions.js:41:38)
  at testCredentials (./src/scripts/modules/wr-db/v2-actions.js:64:33)
  at testCredentialsFn (./src/scripts/modules/wr-db/react/pages/credentials/Credentials.coffee:226:25)
  at testCredentialsFn (./src/scripts/modules/wr-db/react/pages/credentials/CredentialsForm.coffee:66:17)
  at listener (./src/scripts/react/common/TestCredentialsButtonGroup.coffee:30:11)
...
(16 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
Stara vec.
