### ISSUE TITLE
Invariant Violation: Cannot find a route named "ex-db-generic-keboola.ex-google-bigquery"

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#820]
https://sentry.io/keboola/keboola-connection-ui/issues/222253256/

```
Invariant Violation: Cannot find a route named "ex-db-generic-keboola.ex-google-bigquery"
  at transitionTo (./src/scripts/modules/ex-google-bigquery/react/components/HeaderButtons.jsx:80:9)
  at handleDelete (./src/scripts/modules/ex-google-bigquery/react/components/HeaderButtons.jsx:50:33)
  at onDeleteFn (./src/scripts/modules/ex-google-bigquery/react/components/QueryDeleteButton.jsx:33:38)
  at onConfirm (./src/scripts/react/common/ConfirmModal.coffee:33:11)
  at HTMLDocument.nrWrapper (/admin/projects/232/extractors/keboola.ex-google-bigquery/239246294/oauth-redirect:5:11537)
...
(19 additional frame(s) were not displayed)
```

**Comment by ondrejhlavacek** [comment]
je to tenhle button

![image](https://cloud.githubusercontent.com/assets/497675/23156729/73304668-f818-11e6-9562-31f5996409b2.png)

**Comment by ErikZigo** [comment]
diky ja se na to pak podivam

**Comment by ErikZigo** [comment]
Opraveno
